// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: api/v1/common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ComponentType identifies the type of component being executed.
// Shared between Execution Engine and Worker Coordinator.
type ComponentType int32

const (
	ComponentType_COMPONENT_TYPE_UNSPECIFIED ComponentType = 0
	ComponentType_COMPONENT_TYPE_FUNCTION    ComponentType = 1
	ComponentType_COMPONENT_TYPE_FLOW        ComponentType = 2
	ComponentType_COMPONENT_TYPE_OBJECT      ComponentType = 3
	ComponentType_COMPONENT_TYPE_TASK        ComponentType = 4
	ComponentType_COMPONENT_TYPE_WORKFLOW    ComponentType = 5
	ComponentType_COMPONENT_TYPE_AGENT       ComponentType = 6
	ComponentType_COMPONENT_TYPE_TOOL        ComponentType = 7
	ComponentType_COMPONENT_TYPE_MCP         ComponentType = 8
	ComponentType_COMPONENT_TYPE_ENTITY      ComponentType = 9
	ComponentType_COMPONENT_TYPE_SCORER      ComponentType = 10
)

// Enum value maps for ComponentType.
var (
	ComponentType_name = map[int32]string{
		0:  "COMPONENT_TYPE_UNSPECIFIED",
		1:  "COMPONENT_TYPE_FUNCTION",
		2:  "COMPONENT_TYPE_FLOW",
		3:  "COMPONENT_TYPE_OBJECT",
		4:  "COMPONENT_TYPE_TASK",
		5:  "COMPONENT_TYPE_WORKFLOW",
		6:  "COMPONENT_TYPE_AGENT",
		7:  "COMPONENT_TYPE_TOOL",
		8:  "COMPONENT_TYPE_MCP",
		9:  "COMPONENT_TYPE_ENTITY",
		10: "COMPONENT_TYPE_SCORER",
	}
	ComponentType_value = map[string]int32{
		"COMPONENT_TYPE_UNSPECIFIED": 0,
		"COMPONENT_TYPE_FUNCTION":    1,
		"COMPONENT_TYPE_FLOW":        2,
		"COMPONENT_TYPE_OBJECT":      3,
		"COMPONENT_TYPE_TASK":        4,
		"COMPONENT_TYPE_WORKFLOW":    5,
		"COMPONENT_TYPE_AGENT":       6,
		"COMPONENT_TYPE_TOOL":        7,
		"COMPONENT_TYPE_MCP":         8,
		"COMPONENT_TYPE_ENTITY":      9,
		"COMPONENT_TYPE_SCORER":      10,
	}
)

func (x ComponentType) Enum() *ComponentType {
	p := new(ComponentType)
	*p = x
	return p
}

func (x ComponentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComponentType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_common_proto_enumTypes[0].Descriptor()
}

func (ComponentType) Type() protoreflect.EnumType {
	return &file_api_v1_common_proto_enumTypes[0]
}

func (x ComponentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComponentType.Descriptor instead.
func (ComponentType) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_common_proto_rawDescGZIP(), []int{0}
}

// Priority classifies dispatch SLA independently of delivery mechanism.
// Gateway tags requests based on endpoint: /run|/stream → INTERACTIVE,
// default → NORMAL, /submit|/batch → BATCH. Used by the scheduler's
// headroom reservation model (see dispatch redesign plan).
//
// Shared between Engine and Worker Coordinator so both sides of the wire
// can agree on the priority class without a cross-file import.
type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_INTERACTIVE Priority = 1
	Priority_PRIORITY_NORMAL      Priority = 2
	Priority_PRIORITY_BATCH       Priority = 3
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_INTERACTIVE",
		2: "PRIORITY_NORMAL",
		3: "PRIORITY_BATCH",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_INTERACTIVE": 1,
		"PRIORITY_NORMAL":      2,
		"PRIORITY_BATCH":       3,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_common_proto_enumTypes[1].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_api_v1_common_proto_enumTypes[1]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_common_proto_rawDescGZIP(), []int{1}
}

// WorkerMode declares the data-path style a worker uses to receive
// dispatches. Declared once at registration time; mode mismatches do
// not exist mid-session.
//
//   - PUSH: the coordinator pushes dispatches to the worker over the
//     bidirectional WorkerStream as soon as a slot is free.
//   - PULL: the worker calls PollJobs to claim work itself; the
//     bidirectional WorkerStream is still kept open for control messages
//     (heartbeat, cancellations, WORKER_REPLACED) but no dispatches flow
//     over it.
//
// Default behavior when UNSPECIFIED is PUSH so existing workers (built
// before explicit worker modes) continue to receive dispatches without any client
// changes.
type WorkerMode int32

const (
	WorkerMode_WORKER_MODE_UNSPECIFIED WorkerMode = 0
	WorkerMode_WORKER_MODE_PUSH        WorkerMode = 1
	WorkerMode_WORKER_MODE_PULL        WorkerMode = 2
)

// Enum value maps for WorkerMode.
var (
	WorkerMode_name = map[int32]string{
		0: "WORKER_MODE_UNSPECIFIED",
		1: "WORKER_MODE_PUSH",
		2: "WORKER_MODE_PULL",
	}
	WorkerMode_value = map[string]int32{
		"WORKER_MODE_UNSPECIFIED": 0,
		"WORKER_MODE_PUSH":        1,
		"WORKER_MODE_PULL":        2,
	}
)

func (x WorkerMode) Enum() *WorkerMode {
	p := new(WorkerMode)
	*p = x
	return p
}

func (x WorkerMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_common_proto_enumTypes[2].Descriptor()
}

func (WorkerMode) Type() protoreflect.EnumType {
	return &file_api_v1_common_proto_enumTypes[2]
}

func (x WorkerMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerMode.Descriptor instead.
func (WorkerMode) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_common_proto_rawDescGZIP(), []int{2}
}

// Data type enumeration
type Param_DataType int32

const (
	Param_DATA_TYPE_UNSPECIFIED Param_DataType = 0
	Param_DATA_TYPE_STRING      Param_DataType = 1
	Param_DATA_TYPE_INTEGER     Param_DataType = 2
	Param_DATA_TYPE_FLOAT       Param_DataType = 3
	Param_DATA_TYPE_BOOLEAN     Param_DataType = 4
	Param_DATA_TYPE_ARRAY       Param_DataType = 5
	Param_DATA_TYPE_OBJECT      Param_DataType = 6
	Param_DATA_TYPE_DATETIME    Param_DataType = 7
	Param_DATA_TYPE_DURATION    Param_DataType = 8
)

// Enum value maps for Param_DataType.
var (
	Param_DataType_name = map[int32]string{
		0: "DATA_TYPE_UNSPECIFIED",
		1: "DATA_TYPE_STRING",
		2: "DATA_TYPE_INTEGER",
		3: "DATA_TYPE_FLOAT",
		4: "DATA_TYPE_BOOLEAN",
		5: "DATA_TYPE_ARRAY",
		6: "DATA_TYPE_OBJECT",
		7: "DATA_TYPE_DATETIME",
		8: "DATA_TYPE_DURATION",
	}
	Param_DataType_value = map[string]int32{
		"DATA_TYPE_UNSPECIFIED": 0,
		"DATA_TYPE_STRING":      1,
		"DATA_TYPE_INTEGER":     2,
		"DATA_TYPE_FLOAT":       3,
		"DATA_TYPE_BOOLEAN":     4,
		"DATA_TYPE_ARRAY":       5,
		"DATA_TYPE_OBJECT":      6,
		"DATA_TYPE_DATETIME":    7,
		"DATA_TYPE_DURATION":    8,
	}
)

func (x Param_DataType) Enum() *Param_DataType {
	p := new(Param_DataType)
	*p = x
	return p
}

func (x Param_DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Param_DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_common_proto_enumTypes[3].Descriptor()
}

func (Param_DataType) Type() protoreflect.EnumType {
	return &file_api_v1_common_proto_enumTypes[3]
}

func (x Param_DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Param_DataType.Descriptor instead.
func (Param_DataType) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_common_proto_rawDescGZIP(), []int{0, 0}
}

// RetryKind selects between "fail fast" and "retry with bounded budget".
type RetryPolicy_Kind int32

const (
	RetryPolicy_KIND_UNSPECIFIED RetryPolicy_Kind = 0
	// No coordinator-side retry. The failure response flows back to the
	// caller as soon as it lands. Used for synchronous /run + /stream.
	RetryPolicy_KIND_TERMINAL RetryPolicy_Kind = 1
	// Bounded retry with exponential backoff. The coordinator absorbs
	// the failure response, re-queues the run with `ready_at_ms = now +
	// backoff(attempt)`, and lets the next picker tick re-deliver.
	// Once `attempt >= max_attempts`, the run dead-letters via
	// `run.failed`.
	RetryPolicy_KIND_BOUNDED RetryPolicy_Kind = 2
)

// Enum value maps for RetryPolicy_Kind.
var (
	RetryPolicy_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_TERMINAL",
		2: "KIND_BOUNDED",
	}
	RetryPolicy_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_TERMINAL":    1,
		"KIND_BOUNDED":     2,
	}
)

func (x RetryPolicy_Kind) Enum() *RetryPolicy_Kind {
	p := new(RetryPolicy_Kind)
	*p = x
	return p
}

func (x RetryPolicy_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RetryPolicy_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_common_proto_enumTypes[4].Descriptor()
}

func (RetryPolicy_Kind) Type() protoreflect.EnumType {
	return &file_api_v1_common_proto_enumTypes[4]
}

func (x RetryPolicy_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RetryPolicy_Kind.Descriptor instead.
func (RetryPolicy_Kind) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_common_proto_rawDescGZIP(), []int{4, 0}
}

// Parameter definition
type Param struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DataType    Param_DataType         `protobuf:"varint,3,opt,name=data_type,json=dataType,proto3,enum=api.v1.Param_DataType" json:"data_type,omitempty"`
	// Default value using Any to support multiple types
	DefaultValue *anypb.Any `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Required     bool       `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	ClassName    *string    `protobuf:"bytes,6,opt,name=class_name,json=className,proto3,oneof" json:"class_name,omitempty"`
	// Nested parameters for complex types
	NestedFields  map[string]*Param `protobuf:"bytes,7,rep,name=nested_fields,json=nestedFields,proto3" json:"nested_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Param) Reset() {
	*x = Param{}
	mi := &file_api_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Param) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Param) ProtoMessage() {}

func (x *Param) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Param.ProtoReflect.Descriptor instead.
func (*Param) Descriptor() ([]byte, []int) {
	return file_api_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Param) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Param) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Param) GetDataType() Param_DataType {
	if x != nil {
		return x.DataType
	}
	return Param_DATA_TYPE_UNSPECIFIED
}

func (x *Param) GetDefaultValue() *anypb.Any {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

func (x *Param) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Param) GetClassName() string {
	if x != nil && x.ClassName != nil {
		return *x.ClassName
	}
	return ""
}

func (x *Param) GetNestedFields() map[string]*Param {
	if x != nil {
		return x.NestedFields
	}
	return nil
}

// Schedule configuration
type Schedule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ScheduleConfig:
	//
	//	*Schedule_CronExpression
	//	*Schedule_Interval
	ScheduleConfig isSchedule_ScheduleConfig `protobuf_oneof:"schedule_config"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	mi := &file_api_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_api_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Schedule) GetScheduleConfig() isSchedule_ScheduleConfig {
	if x != nil {
		return x.ScheduleConfig
	}
	return nil
}

func (x *Schedule) GetCronExpression() string {
	if x != nil {
		if x, ok := x.ScheduleConfig.(*Schedule_CronExpression); ok {
			return x.CronExpression
		}
	}
	return ""
}

func (x *Schedule) GetInterval() *durationpb.Duration {
	if x != nil {
		if x, ok := x.ScheduleConfig.(*Schedule_Interval); ok {
			return x.Interval
		}
	}
	return nil
}

type isSchedule_ScheduleConfig interface {
	isSchedule_ScheduleConfig()
}

type Schedule_CronExpression struct {
	CronExpression string `protobuf:"bytes,1,opt,name=cron_expression,json=cronExpression,proto3,oneof"`
}

type Schedule_Interval struct {
	Interval *durationpb.Duration `protobuf:"bytes,2,opt,name=interval,proto3,oneof"`
}

func (*Schedule_CronExpression) isSchedule_ScheduleConfig() {}

func (*Schedule_Interval) isSchedule_ScheduleConfig() {}

type AGNT5Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	Traceback     string                 `protobuf:"bytes,5,opt,name=traceback,proto3" json:"traceback,omitempty"`
	ErrorType     string                 `protobuf:"bytes,6,opt,name=error_type,json=errorType,proto3" json:"error_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AGNT5Error) Reset() {
	*x = AGNT5Error{}
	mi := &file_api_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AGNT5Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AGNT5Error) ProtoMessage() {}

func (x *AGNT5Error) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AGNT5Error.ProtoReflect.Descriptor instead.
func (*AGNT5Error) Descriptor() ([]byte, []int) {
	return file_api_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *AGNT5Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AGNT5Error) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *AGNT5Error) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AGNT5Error) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AGNT5Error) GetTraceback() string {
	if x != nil {
		return x.Traceback
	}
	return ""
}

func (x *AGNT5Error) GetErrorType() string {
	if x != nil {
		return x.ErrorType
	}
	return ""
}

type WorkerCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentType ComponentType          `protobuf:"varint,1,opt,name=component_type,json=componentType,proto3,enum=api.v1.ComponentType" json:"component_type,omitempty"`
	ComponentName string                 `protobuf:"bytes,2,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerCapability) Reset() {
	*x = WorkerCapability{}
	mi := &file_api_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerCapability) ProtoMessage() {}

func (x *WorkerCapability) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerCapability.ProtoReflect.Descriptor instead.
func (*WorkerCapability) Descriptor() ([]byte, []int) {
	return file_api_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *WorkerCapability) GetComponentType() ComponentType {
	if x != nil {
		return x.ComponentType
	}
	return ComponentType_COMPONENT_TYPE_UNSPECIFIED
}

func (x *WorkerCapability) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

// RetryPolicy controls how the coordinator handles a worker-reported
// failure (`success=false`) on a dispatched run. It is independent
// from the lease-expiry retry policy: expiry retries are timeout-driven
// and live in the expiry sweeper; failure retries are response-driven
// and live in the dispatch ack handler.
//
// Set on `DispatchComponentRequest` at gateway ingress with defaults
// derived from the request's priority class:
//
//	INTERACTIVE → TERMINAL  (no runtime retry; client handles)
//	NORMAL      → BOUNDED(max=3, initial_backoff=1s, max_backoff=60s)
//	BATCH       → BOUNDED(max=3, initial_backoff=1s, max_backoff=60s)
//
// Callers can override via request metadata if they need different
// semantics for a specific dispatch.
type RetryPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  RetryPolicy_Kind       `protobuf:"varint,1,opt,name=kind,proto3,enum=api.v1.RetryPolicy_Kind" json:"kind,omitempty"`
	// Total delivery budget. `attempt < max_attempts` still has at least
	// one re-delivery left. Ignored when `kind = TERMINAL`.
	MaxAttempts uint32 `protobuf:"varint,2,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	// First-retry backoff in milliseconds. Doubles per attempt up to
	// `max_backoff_ms`. Ignored when `kind = TERMINAL`.
	InitialBackoffMs uint32 `protobuf:"varint,3,opt,name=initial_backoff_ms,json=initialBackoffMs,proto3" json:"initial_backoff_ms,omitempty"`
	// Backoff cap in milliseconds. Prevents the exponential schedule
	// from blowing past a sane upper bound under high attempt counts.
	MaxBackoffMs  uint32 `protobuf:"varint,4,opt,name=max_backoff_ms,json=maxBackoffMs,proto3" json:"max_backoff_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryPolicy) Reset() {
	*x = RetryPolicy{}
	mi := &file_api_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicy) ProtoMessage() {}

func (x *RetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPolicy.ProtoReflect.Descriptor instead.
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return file_api_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *RetryPolicy) GetKind() RetryPolicy_Kind {
	if x != nil {
		return x.Kind
	}
	return RetryPolicy_KIND_UNSPECIFIED
}

func (x *RetryPolicy) GetMaxAttempts() uint32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *RetryPolicy) GetInitialBackoffMs() uint32 {
	if x != nil {
		return x.InitialBackoffMs
	}
	return 0
}

func (x *RetryPolicy) GetMaxBackoffMs() uint32 {
	if x != nil {
		return x.MaxBackoffMs
	}
	return 0
}

var File_api_v1_common_proto protoreflect.FileDescriptor

const file_api_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x13api/v1/common.proto\x12\x06api.v1\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\"\xee\x04\n" +
	"\x05Param\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x123\n" +
	"\tdata_type\x18\x03 \x01(\x0e2\x16.api.v1.Param.DataTypeR\bdataType\x129\n" +
	"\rdefault_value\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\fdefaultValue\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12\"\n" +
	"\n" +
	"class_name\x18\x06 \x01(\tH\x00R\tclassName\x88\x01\x01\x12D\n" +
	"\rnested_fields\x18\a \x03(\v2\x1f.api.v1.Param.NestedFieldsEntryR\fnestedFields\x1aN\n" +
	"\x11NestedFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.api.v1.ParamR\x05value:\x028\x01\"\xd9\x01\n" +
	"\bDataType\x12\x19\n" +
	"\x15DATA_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10DATA_TYPE_STRING\x10\x01\x12\x15\n" +
	"\x11DATA_TYPE_INTEGER\x10\x02\x12\x13\n" +
	"\x0fDATA_TYPE_FLOAT\x10\x03\x12\x15\n" +
	"\x11DATA_TYPE_BOOLEAN\x10\x04\x12\x13\n" +
	"\x0fDATA_TYPE_ARRAY\x10\x05\x12\x14\n" +
	"\x10DATA_TYPE_OBJECT\x10\x06\x12\x16\n" +
	"\x12DATA_TYPE_DATETIME\x10\a\x12\x16\n" +
	"\x12DATA_TYPE_DURATION\x10\bB\r\n" +
	"\v_class_name\"\x81\x01\n" +
	"\bSchedule\x12)\n" +
	"\x0fcron_expression\x18\x01 \x01(\tH\x00R\x0ecronExpression\x127\n" +
	"\binterval\x18\x02 \x01(\v2\x19.google.protobuf.DurationH\x00R\bintervalB\x11\n" +
	"\x0fschedule_config\"\xba\x01\n" +
	"\n" +
	"AGNT5Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12\x1c\n" +
	"\ttraceback\x18\x05 \x01(\tR\ttraceback\x12\x1d\n" +
	"\n" +
	"error_type\x18\x06 \x01(\tR\terrorType\"w\n" +
	"\x10WorkerCapability\x12<\n" +
	"\x0ecomponent_type\x18\x01 \x01(\x0e2\x15.api.v1.ComponentTypeR\rcomponentType\x12%\n" +
	"\x0ecomponent_name\x18\x02 \x01(\tR\rcomponentName\"\xf5\x01\n" +
	"\vRetryPolicy\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.api.v1.RetryPolicy.KindR\x04kind\x12!\n" +
	"\fmax_attempts\x18\x02 \x01(\rR\vmaxAttempts\x12,\n" +
	"\x12initial_backoff_ms\x18\x03 \x01(\rR\x10initialBackoffMs\x12$\n" +
	"\x0emax_backoff_ms\x18\x04 \x01(\rR\fmaxBackoffMs\"A\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rKIND_TERMINAL\x10\x01\x12\x10\n" +
	"\fKIND_BOUNDED\x10\x02*\xb7\x02\n" +
	"\rComponentType\x12\x1e\n" +
	"\x1aCOMPONENT_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17COMPONENT_TYPE_FUNCTION\x10\x01\x12\x17\n" +
	"\x13COMPONENT_TYPE_FLOW\x10\x02\x12\x19\n" +
	"\x15COMPONENT_TYPE_OBJECT\x10\x03\x12\x17\n" +
	"\x13COMPONENT_TYPE_TASK\x10\x04\x12\x1b\n" +
	"\x17COMPONENT_TYPE_WORKFLOW\x10\x05\x12\x18\n" +
	"\x14COMPONENT_TYPE_AGENT\x10\x06\x12\x17\n" +
	"\x13COMPONENT_TYPE_TOOL\x10\a\x12\x16\n" +
	"\x12COMPONENT_TYPE_MCP\x10\b\x12\x19\n" +
	"\x15COMPONENT_TYPE_ENTITY\x10\t\x12\x19\n" +
	"\x15COMPONENT_TYPE_SCORER\x10\n" +
	"*g\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PRIORITY_INTERACTIVE\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_NORMAL\x10\x02\x12\x12\n" +
	"\x0ePRIORITY_BATCH\x10\x03*U\n" +
	"\n" +
	"WorkerMode\x12\x1b\n" +
	"\x17WORKER_MODE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10WORKER_MODE_PUSH\x10\x01\x12\x14\n" +
	"\x10WORKER_MODE_PULL\x10\x02B%Z#agnt5.dev/platform/pkg/pb/api/v1;v1b\x06proto3"

var (
	file_api_v1_common_proto_rawDescOnce sync.Once
	file_api_v1_common_proto_rawDescData []byte
)

func file_api_v1_common_proto_rawDescGZIP() []byte {
	file_api_v1_common_proto_rawDescOnce.Do(func() {
		file_api_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_common_proto_rawDesc), len(file_api_v1_common_proto_rawDesc)))
	})
	return file_api_v1_common_proto_rawDescData
}

var file_api_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_api_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_v1_common_proto_goTypes = []any{
	(ComponentType)(0),          // 0: api.v1.ComponentType
	(Priority)(0),               // 1: api.v1.Priority
	(WorkerMode)(0),             // 2: api.v1.WorkerMode
	(Param_DataType)(0),         // 3: api.v1.Param.DataType
	(RetryPolicy_Kind)(0),       // 4: api.v1.RetryPolicy.Kind
	(*Param)(nil),               // 5: api.v1.Param
	(*Schedule)(nil),            // 6: api.v1.Schedule
	(*AGNT5Error)(nil),          // 7: api.v1.AGNT5Error
	(*WorkerCapability)(nil),    // 8: api.v1.WorkerCapability
	(*RetryPolicy)(nil),         // 9: api.v1.RetryPolicy
	nil,                         // 10: api.v1.Param.NestedFieldsEntry
	(*anypb.Any)(nil),           // 11: google.protobuf.Any
	(*durationpb.Duration)(nil), // 12: google.protobuf.Duration
}
var file_api_v1_common_proto_depIdxs = []int32{
	3,  // 0: api.v1.Param.data_type:type_name -> api.v1.Param.DataType
	11, // 1: api.v1.Param.default_value:type_name -> google.protobuf.Any
	10, // 2: api.v1.Param.nested_fields:type_name -> api.v1.Param.NestedFieldsEntry
	12, // 3: api.v1.Schedule.interval:type_name -> google.protobuf.Duration
	0,  // 4: api.v1.WorkerCapability.component_type:type_name -> api.v1.ComponentType
	4,  // 5: api.v1.RetryPolicy.kind:type_name -> api.v1.RetryPolicy.Kind
	5,  // 6: api.v1.Param.NestedFieldsEntry.value:type_name -> api.v1.Param
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_v1_common_proto_init() }
func file_api_v1_common_proto_init() {
	if File_api_v1_common_proto != nil {
		return
	}
	file_api_v1_common_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_v1_common_proto_msgTypes[1].OneofWrappers = []any{
		(*Schedule_CronExpression)(nil),
		(*Schedule_Interval)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_common_proto_rawDesc), len(file_api_v1_common_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_common_proto_goTypes,
		DependencyIndexes: file_api_v1_common_proto_depIdxs,
		EnumInfos:         file_api_v1_common_proto_enumTypes,
		MessageInfos:      file_api_v1_common_proto_msgTypes,
	}.Build()
	File_api_v1_common_proto = out.File
	file_api_v1_common_proto_goTypes = nil
	file_api_v1_common_proto_depIdxs = nil
}
