// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.32.1
// source: api/v1/engine.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EngineService_Append_FullMethodName                    = "/api.v1.EngineService/Append"
	EngineService_AppendBatch_FullMethodName               = "/api.v1.EngineService/AppendBatch"
	EngineService_Checkpoint_FullMethodName                = "/api.v1.EngineService/Checkpoint"
	EngineService_BeginActivation_FullMethodName           = "/api.v1.EngineService/BeginActivation"
	EngineService_CompleteActivation_FullMethodName        = "/api.v1.EngineService/CompleteActivation"
	EngineService_FailActivation_FullMethodName            = "/api.v1.EngineService/FailActivation"
	EngineService_EventStream_FullMethodName               = "/api.v1.EngineService/EventStream"
	EngineService_PollJobs_FullMethodName                  = "/api.v1.EngineService/PollJobs"
	EngineService_RegisterWorkerSession_FullMethodName     = "/api.v1.EngineService/RegisterWorkerSession"
	EngineService_PollJob_FullMethodName                   = "/api.v1.EngineService/PollJob"
	EngineService_RenewJobLease_FullMethodName             = "/api.v1.EngineService/RenewJobLease"
	EngineService_ReportWorkerCapacity_FullMethodName      = "/api.v1.EngineService/ReportWorkerCapacity"
	EngineService_CompleteJob_FullMethodName               = "/api.v1.EngineService/CompleteJob"
	EngineService_ReadByRunID_FullMethodName               = "/api.v1.EngineService/ReadByRunID"
	EngineService_FindByStepKey_FullMethodName             = "/api.v1.EngineService/FindByStepKey"
	EngineService_GetRun_FullMethodName                    = "/api.v1.EngineService/GetRun"
	EngineService_ListRoutingWorkers_FullMethodName        = "/api.v1.EngineService/ListRoutingWorkers"
	EngineService_Tail_FullMethodName                      = "/api.v1.EngineService/Tail"
	EngineService_GetEntityState_FullMethodName            = "/api.v1.EngineService/GetEntityState"
	EngineService_PutEntityState_FullMethodName            = "/api.v1.EngineService/PutEntityState"
	EngineService_GetApproval_FullMethodName               = "/api.v1.EngineService/GetApproval"
	EngineService_ListApprovals_FullMethodName             = "/api.v1.EngineService/ListApprovals"
	EngineService_GetSignal_FullMethodName                 = "/api.v1.EngineService/GetSignal"
	EngineService_LookupSignal_FullMethodName              = "/api.v1.EngineService/LookupSignal"
	EngineService_ListSignals_FullMethodName               = "/api.v1.EngineService/ListSignals"
	EngineService_GetTimer_FullMethodName                  = "/api.v1.EngineService/GetTimer"
	EngineService_ListTimers_FullMethodName                = "/api.v1.EngineService/ListTimers"
	EngineService_ListDueTimers_FullMethodName             = "/api.v1.EngineService/ListDueTimers"
	EngineService_GetJob_FullMethodName                    = "/api.v1.EngineService/GetJob"
	EngineService_ListJobsByRun_FullMethodName             = "/api.v1.EngineService/ListJobsByRun"
	EngineService_ListJobsByBatch_FullMethodName           = "/api.v1.EngineService/ListJobsByBatch"
	EngineService_GetBatch_FullMethodName                  = "/api.v1.EngineService/GetBatch"
	EngineService_GetSession_FullMethodName                = "/api.v1.EngineService/GetSession"
	EngineService_ListSessions_FullMethodName              = "/api.v1.EngineService/ListSessions"
	EngineService_GetMessage_FullMethodName                = "/api.v1.EngineService/GetMessage"
	EngineService_ListMessagesByCorrelation_FullMethodName = "/api.v1.EngineService/ListMessagesByCorrelation"
	EngineService_ListRuns_FullMethodName                  = "/api.v1.EngineService/ListRuns"
	EngineService_GetRunStats_FullMethodName               = "/api.v1.EngineService/GetRunStats"
	EngineService_ListEvents_FullMethodName                = "/api.v1.EngineService/ListEvents"
	EngineService_GetStatus_FullMethodName                 = "/api.v1.EngineService/GetStatus"
)

// EngineServiceClient is the client API for EngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EngineService is the core orchestration and storage engine.
// SDK workers connect here for all hot-path operations:
// event writes, memoization lookups, run state reads.
type EngineServiceClient interface {
	// Append a single record to the journal log.
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error)
	// Append multiple records atomically when they route to one journal
	// partition. A cross-partition request is rejected before mutation.
	AppendBatch(ctx context.Context, in *AppendBatchRequest, opts ...grpc.CallOption) (*AppendBatchResponse, error)
	// Checkpoint persists a durable step checkpoint and returns memoization status.
	// On STEP_STARTED, looks up prior completion by step_key and returns cached output
	// if found. On STEP_COMPLETED/STEP_FAILED, appends a record to the journal.
	Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error)
	// BeginActivation atomically admits or replays one logical durable activation.
	// The journal aggregate, not a projection, decides the returned outcome.
	BeginActivation(ctx context.Context, in *BeginActivationRequest, opts ...grpc.CallOption) (*BeginActivationResponse, error)
	// CompleteActivation commits one fenced logical result together with its state
	// mutations and durable outbox intents.
	CompleteActivation(ctx context.Context, in *CompleteActivationRequest, opts ...grpc.CallOption) (*CompleteActivationResponse, error)
	// FailActivation records one fenced failure and its retry/uncertainty decision.
	FailActivation(ctx context.Context, in *FailActivationRequest, opts ...grpc.CallOption) (*FailActivationResponse, error)
	// EventStream accepts a stream of ephemeral events (tokens, progress, logs)
	// from SDK workers. No journal persistence — real-time SSE delivery only.
	EventStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EventStreamMessage, EventStreamAck], error)
	// PollJobs claims pending jobs from the durable queue for a worker.
	PollJobs(ctx context.Context, in *PollJobsRequest, opts ...grpc.CallOption) (*PollJobsResponse, error)
	// RegisterWorkerSession binds a worker identity to a deployment lane before
	// parked single-job polling. SPIFFE/SPIRE can later authenticate the same
	// worker identity; the session remains useful for policy and rollout state.
	RegisterWorkerSession(ctx context.Context, in *RegisterWorkerSessionRequest, opts ...grpc.CallOption) (*RegisterWorkerSessionResponse, error)
	// PollJob parks a single worker slot until one job is available or wait_ms
	// elapses. Empty response means timeout.
	PollJob(ctx context.Context, in *PollJobRequest, opts ...grpc.CallOption) (*PollJobResponse, error)
	// RenewJobLease extends the active lease for a currently assigned job.
	RenewJobLease(ctx context.Context, in *RenewJobLeaseRequest, opts ...grpc.CallOption) (*RenewJobLeaseResponse, error)
	// ReportWorkerCapacity publishes the worker's current pull-slot state for
	// autoscaling and heartbeat freshness.
	ReportWorkerCapacity(ctx context.Context, in *ReportWorkerCapacityRequest, opts ...grpc.CallOption) (*ReportWorkerCapacityResponse, error)
	// CompleteJob reports the result of a previously polled job.
	CompleteJob(ctx context.Context, in *CompleteJobRequest, opts ...grpc.CallOption) (*CompleteJobResponse, error)
	// Read all events for a run, ordered by timestamp.
	ReadByRunID(ctx context.Context, in *ReadByRunIDRequest, opts ...grpc.CallOption) (*ReadByRunIDResponse, error)
	// Find a completed step by its memoization key.
	FindByStepKey(ctx context.Context, in *FindByStepKeyRequest, opts ...grpc.CallOption) (*FindByStepKeyResponse, error)
	// Get the current state of a run.
	GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*GetRunResponse, error)
	// List live worker routing entries for an exact route key.
	ListRoutingWorkers(ctx context.Context, in *ListRoutingWorkersRequest, opts ...grpc.CallOption) (*ListRoutingWorkersResponse, error)
	// Tail the log from a given offset. Server-streaming.
	Tail(ctx context.Context, in *TailRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TailResponse], error)
	// Get entity state by scoped key.
	GetEntityState(ctx context.Context, in *GetEntityStateRequest, opts ...grpc.CallOption) (*GetEntityStateResponse, error)
	// Save entity state. Appends a workflow.state.changed record to the journal,
	// which the processor materializes. Supports optimistic locking via expected_version.
	PutEntityState(ctx context.Context, in *PutEntityStateRequest, opts ...grpc.CallOption) (*PutEntityStateResponse, error)
	GetApproval(ctx context.Context, in *GetApprovalRequest, opts ...grpc.CallOption) (*GetApprovalResponse, error)
	ListApprovals(ctx context.Context, in *EngineListApprovalsRequest, opts ...grpc.CallOption) (*EngineListApprovalsResponse, error)
	GetSignal(ctx context.Context, in *GetSignalRequest, opts ...grpc.CallOption) (*GetSignalResponse, error)
	LookupSignal(ctx context.Context, in *LookupSignalRequest, opts ...grpc.CallOption) (*LookupSignalResponse, error)
	ListSignals(ctx context.Context, in *ListSignalsRequest, opts ...grpc.CallOption) (*ListSignalsResponse, error)
	GetTimer(ctx context.Context, in *GetTimerRequest, opts ...grpc.CallOption) (*GetTimerResponse, error)
	ListTimers(ctx context.Context, in *ListTimersRequest, opts ...grpc.CallOption) (*ListTimersResponse, error)
	ListDueTimers(ctx context.Context, in *ListDueTimersRequest, opts ...grpc.CallOption) (*ListDueTimersResponse, error)
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error)
	ListJobsByRun(ctx context.Context, in *ListJobsByRunRequest, opts ...grpc.CallOption) (*ListJobsByRunResponse, error)
	ListJobsByBatch(ctx context.Context, in *ListJobsByBatchRequest, opts ...grpc.CallOption) (*ListJobsByBatchResponse, error)
	GetBatch(ctx context.Context, in *GetBatchRequest, opts ...grpc.CallOption) (*GetBatchResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error)
	ListMessagesByCorrelation(ctx context.Context, in *ListMessagesByCorrelationRequest, opts ...grpc.CallOption) (*ListMessagesByCorrelationResponse, error)
	// List runs with filtering and pagination. Reads from S3 Parquet via DuckDB.
	ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error)
	// Get aggregated run statistics (count by status, component type).
	GetRunStats(ctx context.Context, in *GetRunStatsRequest, opts ...grpc.CallOption) (*GetRunStatsResponse, error)
	// List inbound events a project received, newest-first. Backs the
	// Studio "Events" page. Reads the local events hot index (no cold tier
	// today); each item is a compact summary, full payload fetched via
	// ReadByRunId on the event_run_id.
	ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error)
	// Get engine cluster status.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
}

type engineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineServiceClient(cc grpc.ClientConnInterface) EngineServiceClient {
	return &engineServiceClient{cc}
}

func (c *engineServiceClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendResponse)
	err := c.cc.Invoke(ctx, EngineService_Append_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) AppendBatch(ctx context.Context, in *AppendBatchRequest, opts ...grpc.CallOption) (*AppendBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendBatchResponse)
	err := c.cc.Invoke(ctx, EngineService_AppendBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointResponse)
	err := c.cc.Invoke(ctx, EngineService_Checkpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) BeginActivation(ctx context.Context, in *BeginActivationRequest, opts ...grpc.CallOption) (*BeginActivationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginActivationResponse)
	err := c.cc.Invoke(ctx, EngineService_BeginActivation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) CompleteActivation(ctx context.Context, in *CompleteActivationRequest, opts ...grpc.CallOption) (*CompleteActivationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteActivationResponse)
	err := c.cc.Invoke(ctx, EngineService_CompleteActivation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) FailActivation(ctx context.Context, in *FailActivationRequest, opts ...grpc.CallOption) (*FailActivationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FailActivationResponse)
	err := c.cc.Invoke(ctx, EngineService_FailActivation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) EventStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EventStreamMessage, EventStreamAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EngineService_ServiceDesc.Streams[0], EngineService_EventStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventStreamMessage, EventStreamAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_EventStreamClient = grpc.ClientStreamingClient[EventStreamMessage, EventStreamAck]

func (c *engineServiceClient) PollJobs(ctx context.Context, in *PollJobsRequest, opts ...grpc.CallOption) (*PollJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollJobsResponse)
	err := c.cc.Invoke(ctx, EngineService_PollJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) RegisterWorkerSession(ctx context.Context, in *RegisterWorkerSessionRequest, opts ...grpc.CallOption) (*RegisterWorkerSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterWorkerSessionResponse)
	err := c.cc.Invoke(ctx, EngineService_RegisterWorkerSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) PollJob(ctx context.Context, in *PollJobRequest, opts ...grpc.CallOption) (*PollJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollJobResponse)
	err := c.cc.Invoke(ctx, EngineService_PollJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) RenewJobLease(ctx context.Context, in *RenewJobLeaseRequest, opts ...grpc.CallOption) (*RenewJobLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewJobLeaseResponse)
	err := c.cc.Invoke(ctx, EngineService_RenewJobLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) ReportWorkerCapacity(ctx context.Context, in *ReportWorkerCapacityRequest, opts ...grpc.CallOption) (*ReportWorkerCapacityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportWorkerCapacityResponse)
	err := c.cc.Invoke(ctx, EngineService_ReportWorkerCapacity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) CompleteJob(ctx context.Context, in *CompleteJobRequest, opts ...grpc.CallOption) (*CompleteJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteJobResponse)
	err := c.cc.Invoke(ctx, EngineService_CompleteJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) ReadByRunID(ctx context.Context, in *ReadByRunIDRequest, opts ...grpc.CallOption) (*ReadByRunIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadByRunIDResponse)
	err := c.cc.Invoke(ctx, EngineService_ReadByRunID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) FindByStepKey(ctx context.Context, in *FindByStepKeyRequest, opts ...grpc.CallOption) (*FindByStepKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindByStepKeyResponse)
	err := c.cc.Invoke(ctx, EngineService_FindByStepKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*GetRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunResponse)
	err := c.cc.Invoke(ctx, EngineService_GetRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) ListRoutingWorkers(ctx context.Context, in *ListRoutingWorkersRequest, opts ...grpc.CallOption) (*ListRoutingWorkersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoutingWorkersResponse)
	err := c.cc.Invoke(ctx, EngineService_ListRoutingWorkers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) Tail(ctx context.Context, in *TailRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TailResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EngineService_ServiceDesc.Streams[1], EngineService_Tail_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TailRequest, TailResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_TailClient = grpc.ServerStreamingClient[TailResponse]

func (c *engineServiceClient) GetEntityState(ctx context.Context, in *GetEntityStateRequest, opts ...grpc.CallOption) (*GetEntityStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEntityStateResponse)
	err := c.cc.Invoke(ctx, EngineService_GetEntityState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) PutEntityState(ctx context.Context, in *PutEntityStateRequest, opts ...grpc.CallOption) (*PutEntityStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutEntityStateResponse)
	err := c.cc.Invoke(ctx, EngineService_PutEntityState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) GetApproval(ctx context.Context, in *GetApprovalRequest, opts ...grpc.CallOption) (*GetApprovalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApprovalResponse)
	err := c.cc.Invoke(ctx, EngineService_GetApproval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) ListApprovals(ctx context.Context, in *EngineListApprovalsRequest, opts ...grpc.CallOption) (*EngineListApprovalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EngineListApprovalsResponse)
	err := c.cc.Invoke(ctx, EngineService_ListApprovals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) GetSignal(ctx context.Context, in *GetSignalRequest, opts ...grpc.CallOption) (*GetSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSignalResponse)
	err := c.cc.Invoke(ctx, EngineService_GetSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) LookupSignal(ctx context.Context, in *LookupSignalRequest, opts ...grpc.CallOption) (*LookupSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupSignalResponse)
	err := c.cc.Invoke(ctx, EngineService_LookupSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) ListSignals(ctx context.Context, in *ListSignalsRequest, opts ...grpc.CallOption) (*ListSignalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSignalsResponse)
	err := c.cc.Invoke(ctx, EngineService_ListSignals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) GetTimer(ctx context.Context, in *GetTimerRequest, opts ...grpc.CallOption) (*GetTimerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTimerResponse)
	err := c.cc.Invoke(ctx, EngineService_GetTimer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) ListTimers(ctx context.Context, in *ListTimersRequest, opts ...grpc.CallOption) (*ListTimersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTimersResponse)
	err := c.cc.Invoke(ctx, EngineService_ListTimers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) ListDueTimers(ctx context.Context, in *ListDueTimersRequest, opts ...grpc.CallOption) (*ListDueTimersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDueTimersResponse)
	err := c.cc.Invoke(ctx, EngineService_ListDueTimers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobResponse)
	err := c.cc.Invoke(ctx, EngineService_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) ListJobsByRun(ctx context.Context, in *ListJobsByRunRequest, opts ...grpc.CallOption) (*ListJobsByRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobsByRunResponse)
	err := c.cc.Invoke(ctx, EngineService_ListJobsByRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) ListJobsByBatch(ctx context.Context, in *ListJobsByBatchRequest, opts ...grpc.CallOption) (*ListJobsByBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobsByBatchResponse)
	err := c.cc.Invoke(ctx, EngineService_ListJobsByBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) GetBatch(ctx context.Context, in *GetBatchRequest, opts ...grpc.CallOption) (*GetBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBatchResponse)
	err := c.cc.Invoke(ctx, EngineService_GetBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, EngineService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, EngineService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageResponse)
	err := c.cc.Invoke(ctx, EngineService_GetMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) ListMessagesByCorrelation(ctx context.Context, in *ListMessagesByCorrelationRequest, opts ...grpc.CallOption) (*ListMessagesByCorrelationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMessagesByCorrelationResponse)
	err := c.cc.Invoke(ctx, EngineService_ListMessagesByCorrelation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunsResponse)
	err := c.cc.Invoke(ctx, EngineService_ListRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) GetRunStats(ctx context.Context, in *GetRunStatsRequest, opts ...grpc.CallOption) (*GetRunStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunStatsResponse)
	err := c.cc.Invoke(ctx, EngineService_GetRunStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, EngineService_ListEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, EngineService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngineServiceServer is the server API for EngineService service.
// All implementations must embed UnimplementedEngineServiceServer
// for forward compatibility.
//
// EngineService is the core orchestration and storage engine.
// SDK workers connect here for all hot-path operations:
// event writes, memoization lookups, run state reads.
type EngineServiceServer interface {
	// Append a single record to the journal log.
	Append(context.Context, *AppendRequest) (*AppendResponse, error)
	// Append multiple records atomically when they route to one journal
	// partition. A cross-partition request is rejected before mutation.
	AppendBatch(context.Context, *AppendBatchRequest) (*AppendBatchResponse, error)
	// Checkpoint persists a durable step checkpoint and returns memoization status.
	// On STEP_STARTED, looks up prior completion by step_key and returns cached output
	// if found. On STEP_COMPLETED/STEP_FAILED, appends a record to the journal.
	Checkpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error)
	// BeginActivation atomically admits or replays one logical durable activation.
	// The journal aggregate, not a projection, decides the returned outcome.
	BeginActivation(context.Context, *BeginActivationRequest) (*BeginActivationResponse, error)
	// CompleteActivation commits one fenced logical result together with its state
	// mutations and durable outbox intents.
	CompleteActivation(context.Context, *CompleteActivationRequest) (*CompleteActivationResponse, error)
	// FailActivation records one fenced failure and its retry/uncertainty decision.
	FailActivation(context.Context, *FailActivationRequest) (*FailActivationResponse, error)
	// EventStream accepts a stream of ephemeral events (tokens, progress, logs)
	// from SDK workers. No journal persistence — real-time SSE delivery only.
	EventStream(grpc.ClientStreamingServer[EventStreamMessage, EventStreamAck]) error
	// PollJobs claims pending jobs from the durable queue for a worker.
	PollJobs(context.Context, *PollJobsRequest) (*PollJobsResponse, error)
	// RegisterWorkerSession binds a worker identity to a deployment lane before
	// parked single-job polling. SPIFFE/SPIRE can later authenticate the same
	// worker identity; the session remains useful for policy and rollout state.
	RegisterWorkerSession(context.Context, *RegisterWorkerSessionRequest) (*RegisterWorkerSessionResponse, error)
	// PollJob parks a single worker slot until one job is available or wait_ms
	// elapses. Empty response means timeout.
	PollJob(context.Context, *PollJobRequest) (*PollJobResponse, error)
	// RenewJobLease extends the active lease for a currently assigned job.
	RenewJobLease(context.Context, *RenewJobLeaseRequest) (*RenewJobLeaseResponse, error)
	// ReportWorkerCapacity publishes the worker's current pull-slot state for
	// autoscaling and heartbeat freshness.
	ReportWorkerCapacity(context.Context, *ReportWorkerCapacityRequest) (*ReportWorkerCapacityResponse, error)
	// CompleteJob reports the result of a previously polled job.
	CompleteJob(context.Context, *CompleteJobRequest) (*CompleteJobResponse, error)
	// Read all events for a run, ordered by timestamp.
	ReadByRunID(context.Context, *ReadByRunIDRequest) (*ReadByRunIDResponse, error)
	// Find a completed step by its memoization key.
	FindByStepKey(context.Context, *FindByStepKeyRequest) (*FindByStepKeyResponse, error)
	// Get the current state of a run.
	GetRun(context.Context, *GetRunRequest) (*GetRunResponse, error)
	// List live worker routing entries for an exact route key.
	ListRoutingWorkers(context.Context, *ListRoutingWorkersRequest) (*ListRoutingWorkersResponse, error)
	// Tail the log from a given offset. Server-streaming.
	Tail(*TailRequest, grpc.ServerStreamingServer[TailResponse]) error
	// Get entity state by scoped key.
	GetEntityState(context.Context, *GetEntityStateRequest) (*GetEntityStateResponse, error)
	// Save entity state. Appends a workflow.state.changed record to the journal,
	// which the processor materializes. Supports optimistic locking via expected_version.
	PutEntityState(context.Context, *PutEntityStateRequest) (*PutEntityStateResponse, error)
	GetApproval(context.Context, *GetApprovalRequest) (*GetApprovalResponse, error)
	ListApprovals(context.Context, *EngineListApprovalsRequest) (*EngineListApprovalsResponse, error)
	GetSignal(context.Context, *GetSignalRequest) (*GetSignalResponse, error)
	LookupSignal(context.Context, *LookupSignalRequest) (*LookupSignalResponse, error)
	ListSignals(context.Context, *ListSignalsRequest) (*ListSignalsResponse, error)
	GetTimer(context.Context, *GetTimerRequest) (*GetTimerResponse, error)
	ListTimers(context.Context, *ListTimersRequest) (*ListTimersResponse, error)
	ListDueTimers(context.Context, *ListDueTimersRequest) (*ListDueTimersResponse, error)
	GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error)
	ListJobsByRun(context.Context, *ListJobsByRunRequest) (*ListJobsByRunResponse, error)
	ListJobsByBatch(context.Context, *ListJobsByBatchRequest) (*ListJobsByBatchResponse, error)
	GetBatch(context.Context, *GetBatchRequest) (*GetBatchResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	GetMessage(context.Context, *GetMessageRequest) (*GetMessageResponse, error)
	ListMessagesByCorrelation(context.Context, *ListMessagesByCorrelationRequest) (*ListMessagesByCorrelationResponse, error)
	// List runs with filtering and pagination. Reads from S3 Parquet via DuckDB.
	ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error)
	// Get aggregated run statistics (count by status, component type).
	GetRunStats(context.Context, *GetRunStatsRequest) (*GetRunStatsResponse, error)
	// List inbound events a project received, newest-first. Backs the
	// Studio "Events" page. Reads the local events hot index (no cold tier
	// today); each item is a compact summary, full payload fetched via
	// ReadByRunId on the event_run_id.
	ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error)
	// Get engine cluster status.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	mustEmbedUnimplementedEngineServiceServer()
}

// UnimplementedEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEngineServiceServer struct{}

func (UnimplementedEngineServiceServer) Append(context.Context, *AppendRequest) (*AppendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedEngineServiceServer) AppendBatch(context.Context, *AppendBatchRequest) (*AppendBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendBatch not implemented")
}
func (UnimplementedEngineServiceServer) Checkpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Checkpoint not implemented")
}
func (UnimplementedEngineServiceServer) BeginActivation(context.Context, *BeginActivationRequest) (*BeginActivationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginActivation not implemented")
}
func (UnimplementedEngineServiceServer) CompleteActivation(context.Context, *CompleteActivationRequest) (*CompleteActivationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteActivation not implemented")
}
func (UnimplementedEngineServiceServer) FailActivation(context.Context, *FailActivationRequest) (*FailActivationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FailActivation not implemented")
}
func (UnimplementedEngineServiceServer) EventStream(grpc.ClientStreamingServer[EventStreamMessage, EventStreamAck]) error {
	return status.Error(codes.Unimplemented, "method EventStream not implemented")
}
func (UnimplementedEngineServiceServer) PollJobs(context.Context, *PollJobsRequest) (*PollJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PollJobs not implemented")
}
func (UnimplementedEngineServiceServer) RegisterWorkerSession(context.Context, *RegisterWorkerSessionRequest) (*RegisterWorkerSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWorkerSession not implemented")
}
func (UnimplementedEngineServiceServer) PollJob(context.Context, *PollJobRequest) (*PollJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PollJob not implemented")
}
func (UnimplementedEngineServiceServer) RenewJobLease(context.Context, *RenewJobLeaseRequest) (*RenewJobLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewJobLease not implemented")
}
func (UnimplementedEngineServiceServer) ReportWorkerCapacity(context.Context, *ReportWorkerCapacityRequest) (*ReportWorkerCapacityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportWorkerCapacity not implemented")
}
func (UnimplementedEngineServiceServer) CompleteJob(context.Context, *CompleteJobRequest) (*CompleteJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteJob not implemented")
}
func (UnimplementedEngineServiceServer) ReadByRunID(context.Context, *ReadByRunIDRequest) (*ReadByRunIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadByRunID not implemented")
}
func (UnimplementedEngineServiceServer) FindByStepKey(context.Context, *FindByStepKeyRequest) (*FindByStepKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByStepKey not implemented")
}
func (UnimplementedEngineServiceServer) GetRun(context.Context, *GetRunRequest) (*GetRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRun not implemented")
}
func (UnimplementedEngineServiceServer) ListRoutingWorkers(context.Context, *ListRoutingWorkersRequest) (*ListRoutingWorkersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoutingWorkers not implemented")
}
func (UnimplementedEngineServiceServer) Tail(*TailRequest, grpc.ServerStreamingServer[TailResponse]) error {
	return status.Error(codes.Unimplemented, "method Tail not implemented")
}
func (UnimplementedEngineServiceServer) GetEntityState(context.Context, *GetEntityStateRequest) (*GetEntityStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntityState not implemented")
}
func (UnimplementedEngineServiceServer) PutEntityState(context.Context, *PutEntityStateRequest) (*PutEntityStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutEntityState not implemented")
}
func (UnimplementedEngineServiceServer) GetApproval(context.Context, *GetApprovalRequest) (*GetApprovalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApproval not implemented")
}
func (UnimplementedEngineServiceServer) ListApprovals(context.Context, *EngineListApprovalsRequest) (*EngineListApprovalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListApprovals not implemented")
}
func (UnimplementedEngineServiceServer) GetSignal(context.Context, *GetSignalRequest) (*GetSignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSignal not implemented")
}
func (UnimplementedEngineServiceServer) LookupSignal(context.Context, *LookupSignalRequest) (*LookupSignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupSignal not implemented")
}
func (UnimplementedEngineServiceServer) ListSignals(context.Context, *ListSignalsRequest) (*ListSignalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSignals not implemented")
}
func (UnimplementedEngineServiceServer) GetTimer(context.Context, *GetTimerRequest) (*GetTimerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTimer not implemented")
}
func (UnimplementedEngineServiceServer) ListTimers(context.Context, *ListTimersRequest) (*ListTimersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTimers not implemented")
}
func (UnimplementedEngineServiceServer) ListDueTimers(context.Context, *ListDueTimersRequest) (*ListDueTimersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDueTimers not implemented")
}
func (UnimplementedEngineServiceServer) GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedEngineServiceServer) ListJobsByRun(context.Context, *ListJobsByRunRequest) (*ListJobsByRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobsByRun not implemented")
}
func (UnimplementedEngineServiceServer) ListJobsByBatch(context.Context, *ListJobsByBatchRequest) (*ListJobsByBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobsByBatch not implemented")
}
func (UnimplementedEngineServiceServer) GetBatch(context.Context, *GetBatchRequest) (*GetBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBatch not implemented")
}
func (UnimplementedEngineServiceServer) GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedEngineServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedEngineServiceServer) GetMessage(context.Context, *GetMessageRequest) (*GetMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessage not implemented")
}
func (UnimplementedEngineServiceServer) ListMessagesByCorrelation(context.Context, *ListMessagesByCorrelationRequest) (*ListMessagesByCorrelationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMessagesByCorrelation not implemented")
}
func (UnimplementedEngineServiceServer) ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRuns not implemented")
}
func (UnimplementedEngineServiceServer) GetRunStats(context.Context, *GetRunStatsRequest) (*GetRunStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRunStats not implemented")
}
func (UnimplementedEngineServiceServer) ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedEngineServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedEngineServiceServer) mustEmbedUnimplementedEngineServiceServer() {}
func (UnimplementedEngineServiceServer) testEmbeddedByValue()                       {}

// UnsafeEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngineServiceServer will
// result in compilation errors.
type UnsafeEngineServiceServer interface {
	mustEmbedUnimplementedEngineServiceServer()
}

func RegisterEngineServiceServer(s grpc.ServiceRegistrar, srv EngineServiceServer) {
	// If the following call panics, it indicates UnimplementedEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EngineService_ServiceDesc, srv)
}

func _EngineService_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_Append_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_AppendBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).AppendBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_AppendBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).AppendBatch(ctx, req.(*AppendBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_Checkpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).Checkpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_Checkpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).Checkpoint(ctx, req.(*CheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_BeginActivation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginActivationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).BeginActivation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_BeginActivation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).BeginActivation(ctx, req.(*BeginActivationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_CompleteActivation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteActivationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).CompleteActivation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_CompleteActivation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).CompleteActivation(ctx, req.(*CompleteActivationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_FailActivation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailActivationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).FailActivation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_FailActivation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).FailActivation(ctx, req.(*FailActivationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_EventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EngineServiceServer).EventStream(&grpc.GenericServerStream[EventStreamMessage, EventStreamAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_EventStreamServer = grpc.ClientStreamingServer[EventStreamMessage, EventStreamAck]

func _EngineService_PollJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).PollJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_PollJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).PollJobs(ctx, req.(*PollJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_RegisterWorkerSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWorkerSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).RegisterWorkerSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_RegisterWorkerSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).RegisterWorkerSession(ctx, req.(*RegisterWorkerSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_PollJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).PollJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_PollJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).PollJob(ctx, req.(*PollJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_RenewJobLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewJobLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).RenewJobLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_RenewJobLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).RenewJobLease(ctx, req.(*RenewJobLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_ReportWorkerCapacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportWorkerCapacityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).ReportWorkerCapacity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_ReportWorkerCapacity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).ReportWorkerCapacity(ctx, req.(*ReportWorkerCapacityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_CompleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).CompleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_CompleteJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).CompleteJob(ctx, req.(*CompleteJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_ReadByRunID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadByRunIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).ReadByRunID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_ReadByRunID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).ReadByRunID(ctx, req.(*ReadByRunIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_FindByStepKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByStepKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).FindByStepKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_FindByStepKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).FindByStepKey(ctx, req.(*FindByStepKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_GetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).GetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_GetRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).GetRun(ctx, req.(*GetRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_ListRoutingWorkers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoutingWorkersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).ListRoutingWorkers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_ListRoutingWorkers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).ListRoutingWorkers(ctx, req.(*ListRoutingWorkersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_Tail_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TailRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EngineServiceServer).Tail(m, &grpc.GenericServerStream[TailRequest, TailResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_TailServer = grpc.ServerStreamingServer[TailResponse]

func _EngineService_GetEntityState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).GetEntityState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_GetEntityState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).GetEntityState(ctx, req.(*GetEntityStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_PutEntityState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutEntityStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).PutEntityState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_PutEntityState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).PutEntityState(ctx, req.(*PutEntityStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_GetApproval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApprovalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).GetApproval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_GetApproval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).GetApproval(ctx, req.(*GetApprovalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_ListApprovals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EngineListApprovalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).ListApprovals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_ListApprovals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).ListApprovals(ctx, req.(*EngineListApprovalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_GetSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).GetSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_GetSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).GetSignal(ctx, req.(*GetSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_LookupSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).LookupSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_LookupSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).LookupSignal(ctx, req.(*LookupSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_ListSignals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSignalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).ListSignals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_ListSignals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).ListSignals(ctx, req.(*ListSignalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_GetTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).GetTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_GetTimer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).GetTimer(ctx, req.(*GetTimerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_ListTimers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTimersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).ListTimers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_ListTimers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).ListTimers(ctx, req.(*ListTimersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_ListDueTimers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDueTimersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).ListDueTimers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_ListDueTimers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).ListDueTimers(ctx, req.(*ListDueTimersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_ListJobsByRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsByRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).ListJobsByRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_ListJobsByRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).ListJobsByRun(ctx, req.(*ListJobsByRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_ListJobsByBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsByBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).ListJobsByBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_ListJobsByBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).ListJobsByBatch(ctx, req.(*ListJobsByBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_GetBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).GetBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_GetBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).GetBatch(ctx, req.(*GetBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_GetMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).GetMessage(ctx, req.(*GetMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_ListMessagesByCorrelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMessagesByCorrelationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).ListMessagesByCorrelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_ListMessagesByCorrelation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).ListMessagesByCorrelation(ctx, req.(*ListMessagesByCorrelationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_ListRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).ListRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_ListRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).ListRuns(ctx, req.(*ListRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_GetRunStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).GetRunStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_GetRunStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).GetRunStats(ctx, req.(*GetRunStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_ListEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).ListEvents(ctx, req.(*ListEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EngineService_ServiceDesc is the grpc.ServiceDesc for EngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.EngineService",
	HandlerType: (*EngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Append",
			Handler:    _EngineService_Append_Handler,
		},
		{
			MethodName: "AppendBatch",
			Handler:    _EngineService_AppendBatch_Handler,
		},
		{
			MethodName: "Checkpoint",
			Handler:    _EngineService_Checkpoint_Handler,
		},
		{
			MethodName: "BeginActivation",
			Handler:    _EngineService_BeginActivation_Handler,
		},
		{
			MethodName: "CompleteActivation",
			Handler:    _EngineService_CompleteActivation_Handler,
		},
		{
			MethodName: "FailActivation",
			Handler:    _EngineService_FailActivation_Handler,
		},
		{
			MethodName: "PollJobs",
			Handler:    _EngineService_PollJobs_Handler,
		},
		{
			MethodName: "RegisterWorkerSession",
			Handler:    _EngineService_RegisterWorkerSession_Handler,
		},
		{
			MethodName: "PollJob",
			Handler:    _EngineService_PollJob_Handler,
		},
		{
			MethodName: "RenewJobLease",
			Handler:    _EngineService_RenewJobLease_Handler,
		},
		{
			MethodName: "ReportWorkerCapacity",
			Handler:    _EngineService_ReportWorkerCapacity_Handler,
		},
		{
			MethodName: "CompleteJob",
			Handler:    _EngineService_CompleteJob_Handler,
		},
		{
			MethodName: "ReadByRunID",
			Handler:    _EngineService_ReadByRunID_Handler,
		},
		{
			MethodName: "FindByStepKey",
			Handler:    _EngineService_FindByStepKey_Handler,
		},
		{
			MethodName: "GetRun",
			Handler:    _EngineService_GetRun_Handler,
		},
		{
			MethodName: "ListRoutingWorkers",
			Handler:    _EngineService_ListRoutingWorkers_Handler,
		},
		{
			MethodName: "GetEntityState",
			Handler:    _EngineService_GetEntityState_Handler,
		},
		{
			MethodName: "PutEntityState",
			Handler:    _EngineService_PutEntityState_Handler,
		},
		{
			MethodName: "GetApproval",
			Handler:    _EngineService_GetApproval_Handler,
		},
		{
			MethodName: "ListApprovals",
			Handler:    _EngineService_ListApprovals_Handler,
		},
		{
			MethodName: "GetSignal",
			Handler:    _EngineService_GetSignal_Handler,
		},
		{
			MethodName: "LookupSignal",
			Handler:    _EngineService_LookupSignal_Handler,
		},
		{
			MethodName: "ListSignals",
			Handler:    _EngineService_ListSignals_Handler,
		},
		{
			MethodName: "GetTimer",
			Handler:    _EngineService_GetTimer_Handler,
		},
		{
			MethodName: "ListTimers",
			Handler:    _EngineService_ListTimers_Handler,
		},
		{
			MethodName: "ListDueTimers",
			Handler:    _EngineService_ListDueTimers_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _EngineService_GetJob_Handler,
		},
		{
			MethodName: "ListJobsByRun",
			Handler:    _EngineService_ListJobsByRun_Handler,
		},
		{
			MethodName: "ListJobsByBatch",
			Handler:    _EngineService_ListJobsByBatch_Handler,
		},
		{
			MethodName: "GetBatch",
			Handler:    _EngineService_GetBatch_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _EngineService_GetSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _EngineService_ListSessions_Handler,
		},
		{
			MethodName: "GetMessage",
			Handler:    _EngineService_GetMessage_Handler,
		},
		{
			MethodName: "ListMessagesByCorrelation",
			Handler:    _EngineService_ListMessagesByCorrelation_Handler,
		},
		{
			MethodName: "ListRuns",
			Handler:    _EngineService_ListRuns_Handler,
		},
		{
			MethodName: "GetRunStats",
			Handler:    _EngineService_GetRunStats_Handler,
		},
		{
			MethodName: "ListEvents",
			Handler:    _EngineService_ListEvents_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _EngineService_GetStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventStream",
			Handler:       _EngineService_EventStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Tail",
			Handler:       _EngineService_Tail_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/v1/engine.proto",
}

const (
	ReplicationService_Store_FullMethodName              = "/api.v1.ReplicationService/Store"
	ReplicationService_GetRecords_FullMethodName         = "/api.v1.ReplicationService/GetRecords"
	ReplicationService_Seal_FullMethodName               = "/api.v1.ReplicationService/Seal"
	ReplicationService_Heartbeat_FullMethodName          = "/api.v1.ReplicationService/Heartbeat"
	ReplicationService_RequestVote_FullMethodName        = "/api.v1.ReplicationService/RequestVote"
	ReplicationService_AnnounceLeader_FullMethodName     = "/api.v1.ReplicationService/AnnounceLeader"
	ReplicationService_ForwardAppend_FullMethodName      = "/api.v1.ReplicationService/ForwardAppend"
	ReplicationService_ForwardAppendV2_FullMethodName    = "/api.v1.ReplicationService/ForwardAppendV2"
	ReplicationService_AddMember_FullMethodName          = "/api.v1.ReplicationService/AddMember"
	ReplicationService_RemoveMember_FullMethodName       = "/api.v1.ReplicationService/RemoveMember"
	ReplicationService_TransferLeadership_FullMethodName = "/api.v1.ReplicationService/TransferLeadership"
)

// ReplicationServiceClient is the client API for ReplicationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ReplicationService handles node-to-node communication
// for quorum replication within a cluster.
type ReplicationServiceClient interface {
	// Store a batch of records on a replica node.
	Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error)
	// Read records from a replica (for catch-up).
	// Server-streaming: response is split into bounded chunks so a large
	// catch-up backlog (hundreds of MB) doesn't blow past h2 frame/buffer
	// limits. Each GetRecordsResponse carries a slice of records; the
	// client concatenates them in stream order.
	GetRecords(ctx context.Context, in *GetRecordsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetRecordsResponse], error)
	// Seal a segment on a replica node.
	Seal(ctx context.Context, in *SealRequest, opts ...grpc.CallOption) (*SealResponse, error)
	// Heartbeat between cluster nodes (liveness + epoch propagation).
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Vote request during sequencer election.
	RequestVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error)
	// Announce new sequencer to all peers after winning election.
	AnnounceLeader(ctx context.Context, in *AnnounceLeaderRequest, opts ...grpc.CallOption) (*AnnounceLeaderResponse, error)
	// Forward a write from a follower to the sequencer.
	ForwardAppend(ctx context.Context, in *ForwardAppendRequest, opts ...grpc.CallOption) (*ForwardAppendResponse, error)
	// Forward a write while preserving the exact per-record append outcome.
	// A distinct method makes mixed-version calls fail before an older server
	// can mutate storage.
	ForwardAppendV2(ctx context.Context, in *ForwardAppendRequest, opts ...grpc.CallOption) (*ForwardAppendResponse, error)
	// Add a member to the cluster (leader only).
	AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*AddMemberResponse, error)
	// Remove a member from the cluster (leader only).
	RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*RemoveMemberResponse, error)
	// Explicitly transfer partition leadership to another live node.
	TransferLeadership(ctx context.Context, in *TransferLeadershipRequest, opts ...grpc.CallOption) (*TransferLeadershipResponse, error)
}

type replicationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicationServiceClient(cc grpc.ClientConnInterface) ReplicationServiceClient {
	return &replicationServiceClient{cc}
}

func (c *replicationServiceClient) Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreResponse)
	err := c.cc.Invoke(ctx, ReplicationService_Store_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationServiceClient) GetRecords(ctx context.Context, in *GetRecordsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetRecordsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ReplicationService_ServiceDesc.Streams[0], ReplicationService_GetRecords_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRecordsRequest, GetRecordsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReplicationService_GetRecordsClient = grpc.ServerStreamingClient[GetRecordsResponse]

func (c *replicationServiceClient) Seal(ctx context.Context, in *SealRequest, opts ...grpc.CallOption) (*SealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SealResponse)
	err := c.cc.Invoke(ctx, ReplicationService_Seal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ReplicationService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationServiceClient) RequestVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoteResponse)
	err := c.cc.Invoke(ctx, ReplicationService_RequestVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationServiceClient) AnnounceLeader(ctx context.Context, in *AnnounceLeaderRequest, opts ...grpc.CallOption) (*AnnounceLeaderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnnounceLeaderResponse)
	err := c.cc.Invoke(ctx, ReplicationService_AnnounceLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationServiceClient) ForwardAppend(ctx context.Context, in *ForwardAppendRequest, opts ...grpc.CallOption) (*ForwardAppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardAppendResponse)
	err := c.cc.Invoke(ctx, ReplicationService_ForwardAppend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationServiceClient) ForwardAppendV2(ctx context.Context, in *ForwardAppendRequest, opts ...grpc.CallOption) (*ForwardAppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardAppendResponse)
	err := c.cc.Invoke(ctx, ReplicationService_ForwardAppendV2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationServiceClient) AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*AddMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMemberResponse)
	err := c.cc.Invoke(ctx, ReplicationService_AddMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationServiceClient) RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*RemoveMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMemberResponse)
	err := c.cc.Invoke(ctx, ReplicationService_RemoveMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationServiceClient) TransferLeadership(ctx context.Context, in *TransferLeadershipRequest, opts ...grpc.CallOption) (*TransferLeadershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferLeadershipResponse)
	err := c.cc.Invoke(ctx, ReplicationService_TransferLeadership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicationServiceServer is the server API for ReplicationService service.
// All implementations must embed UnimplementedReplicationServiceServer
// for forward compatibility.
//
// ReplicationService handles node-to-node communication
// for quorum replication within a cluster.
type ReplicationServiceServer interface {
	// Store a batch of records on a replica node.
	Store(context.Context, *StoreRequest) (*StoreResponse, error)
	// Read records from a replica (for catch-up).
	// Server-streaming: response is split into bounded chunks so a large
	// catch-up backlog (hundreds of MB) doesn't blow past h2 frame/buffer
	// limits. Each GetRecordsResponse carries a slice of records; the
	// client concatenates them in stream order.
	GetRecords(*GetRecordsRequest, grpc.ServerStreamingServer[GetRecordsResponse]) error
	// Seal a segment on a replica node.
	Seal(context.Context, *SealRequest) (*SealResponse, error)
	// Heartbeat between cluster nodes (liveness + epoch propagation).
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Vote request during sequencer election.
	RequestVote(context.Context, *VoteRequest) (*VoteResponse, error)
	// Announce new sequencer to all peers after winning election.
	AnnounceLeader(context.Context, *AnnounceLeaderRequest) (*AnnounceLeaderResponse, error)
	// Forward a write from a follower to the sequencer.
	ForwardAppend(context.Context, *ForwardAppendRequest) (*ForwardAppendResponse, error)
	// Forward a write while preserving the exact per-record append outcome.
	// A distinct method makes mixed-version calls fail before an older server
	// can mutate storage.
	ForwardAppendV2(context.Context, *ForwardAppendRequest) (*ForwardAppendResponse, error)
	// Add a member to the cluster (leader only).
	AddMember(context.Context, *AddMemberRequest) (*AddMemberResponse, error)
	// Remove a member from the cluster (leader only).
	RemoveMember(context.Context, *RemoveMemberRequest) (*RemoveMemberResponse, error)
	// Explicitly transfer partition leadership to another live node.
	TransferLeadership(context.Context, *TransferLeadershipRequest) (*TransferLeadershipResponse, error)
	mustEmbedUnimplementedReplicationServiceServer()
}

// UnimplementedReplicationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReplicationServiceServer struct{}

func (UnimplementedReplicationServiceServer) Store(context.Context, *StoreRequest) (*StoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedReplicationServiceServer) GetRecords(*GetRecordsRequest, grpc.ServerStreamingServer[GetRecordsResponse]) error {
	return status.Error(codes.Unimplemented, "method GetRecords not implemented")
}
func (UnimplementedReplicationServiceServer) Seal(context.Context, *SealRequest) (*SealResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Seal not implemented")
}
func (UnimplementedReplicationServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedReplicationServiceServer) RequestVote(context.Context, *VoteRequest) (*VoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestVote not implemented")
}
func (UnimplementedReplicationServiceServer) AnnounceLeader(context.Context, *AnnounceLeaderRequest) (*AnnounceLeaderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnnounceLeader not implemented")
}
func (UnimplementedReplicationServiceServer) ForwardAppend(context.Context, *ForwardAppendRequest) (*ForwardAppendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardAppend not implemented")
}
func (UnimplementedReplicationServiceServer) ForwardAppendV2(context.Context, *ForwardAppendRequest) (*ForwardAppendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardAppendV2 not implemented")
}
func (UnimplementedReplicationServiceServer) AddMember(context.Context, *AddMemberRequest) (*AddMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMember not implemented")
}
func (UnimplementedReplicationServiceServer) RemoveMember(context.Context, *RemoveMemberRequest) (*RemoveMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMember not implemented")
}
func (UnimplementedReplicationServiceServer) TransferLeadership(context.Context, *TransferLeadershipRequest) (*TransferLeadershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferLeadership not implemented")
}
func (UnimplementedReplicationServiceServer) mustEmbedUnimplementedReplicationServiceServer() {}
func (UnimplementedReplicationServiceServer) testEmbeddedByValue()                            {}

// UnsafeReplicationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicationServiceServer will
// result in compilation errors.
type UnsafeReplicationServiceServer interface {
	mustEmbedUnimplementedReplicationServiceServer()
}

func RegisterReplicationServiceServer(s grpc.ServiceRegistrar, srv ReplicationServiceServer) {
	// If the following call panics, it indicates UnimplementedReplicationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReplicationService_ServiceDesc, srv)
}

func _ReplicationService_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServiceServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicationService_Store_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServiceServer).Store(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicationService_GetRecords_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRecordsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReplicationServiceServer).GetRecords(m, &grpc.GenericServerStream[GetRecordsRequest, GetRecordsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReplicationService_GetRecordsServer = grpc.ServerStreamingServer[GetRecordsResponse]

func _ReplicationService_Seal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServiceServer).Seal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicationService_Seal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServiceServer).Seal(ctx, req.(*SealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicationService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicationService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicationService_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServiceServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicationService_RequestVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServiceServer).RequestVote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicationService_AnnounceLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnnounceLeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServiceServer).AnnounceLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicationService_AnnounceLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServiceServer).AnnounceLeader(ctx, req.(*AnnounceLeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicationService_ForwardAppend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardAppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServiceServer).ForwardAppend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicationService_ForwardAppend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServiceServer).ForwardAppend(ctx, req.(*ForwardAppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicationService_ForwardAppendV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardAppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServiceServer).ForwardAppendV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicationService_ForwardAppendV2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServiceServer).ForwardAppendV2(ctx, req.(*ForwardAppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicationService_AddMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServiceServer).AddMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicationService_AddMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServiceServer).AddMember(ctx, req.(*AddMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicationService_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServiceServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicationService_RemoveMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServiceServer).RemoveMember(ctx, req.(*RemoveMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicationService_TransferLeadership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferLeadershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServiceServer).TransferLeadership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicationService_TransferLeadership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServiceServer).TransferLeadership(ctx, req.(*TransferLeadershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReplicationService_ServiceDesc is the grpc.ServiceDesc for ReplicationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReplicationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.ReplicationService",
	HandlerType: (*ReplicationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _ReplicationService_Store_Handler,
		},
		{
			MethodName: "Seal",
			Handler:    _ReplicationService_Seal_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ReplicationService_Heartbeat_Handler,
		},
		{
			MethodName: "RequestVote",
			Handler:    _ReplicationService_RequestVote_Handler,
		},
		{
			MethodName: "AnnounceLeader",
			Handler:    _ReplicationService_AnnounceLeader_Handler,
		},
		{
			MethodName: "ForwardAppend",
			Handler:    _ReplicationService_ForwardAppend_Handler,
		},
		{
			MethodName: "ForwardAppendV2",
			Handler:    _ReplicationService_ForwardAppendV2_Handler,
		},
		{
			MethodName: "AddMember",
			Handler:    _ReplicationService_AddMember_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _ReplicationService_RemoveMember_Handler,
		},
		{
			MethodName: "TransferLeadership",
			Handler:    _ReplicationService_TransferLeadership_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRecords",
			Handler:       _ReplicationService_GetRecords_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/v1/engine.proto",
}
