// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: api/v1/worker_coordinator.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerCoordinatorService_WorkerStream_FullMethodName                 = "/api.v1.WorkerCoordinatorService/WorkerStream"
	WorkerCoordinatorService_ListWorkers_FullMethodName                  = "/api.v1.WorkerCoordinatorService/ListWorkers"
	WorkerCoordinatorService_DispatchComponent_FullMethodName            = "/api.v1.WorkerCoordinatorService/DispatchComponent"
	WorkerCoordinatorService_DispatchComponentStream_FullMethodName      = "/api.v1.WorkerCoordinatorService/DispatchComponentStream"
	WorkerCoordinatorService_ForwardDispatch_FullMethodName              = "/api.v1.WorkerCoordinatorService/ForwardDispatch"
	WorkerCoordinatorService_ForwardDispatchStream_FullMethodName        = "/api.v1.WorkerCoordinatorService/ForwardDispatchStream"
	WorkerCoordinatorService_ForwardDispatchFireAndForget_FullMethodName = "/api.v1.WorkerCoordinatorService/ForwardDispatchFireAndForget"
	WorkerCoordinatorService_ReleaseActiveDispatch_FullMethodName        = "/api.v1.WorkerCoordinatorService/ReleaseActiveDispatch"
)

// WorkerCoordinatorServiceClient is the client API for WorkerCoordinatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkerCoordinatorService manages worker lifecycle and task dispatch.
//
// All state operations (signals, approvals, timers, checkpoints, journal writes,
// job queue, ephemeral event streams) are handled by EngineService. The coordinator
// is responsible ONLY for:
// - Worker stream lifecycle (registration, heartbeat, dispatch, response routing)
// - Task dispatch and worker selection
// - Inter-coordinator forwarding (disaggregated mode)
type WorkerCoordinatorServiceClient interface {
	// Main stream — bidirectional communication for worker lifecycle and task execution.
	// First message from worker must be ServiceRegistration.
	WorkerStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ServiceMessage, RuntimeMessage], error)
	// List registered workers.
	ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error)
	// Dispatch a component to a registered worker (synchronous, waits for response).
	DispatchComponent(ctx context.Context, in *DispatchComponentRequest, opts ...grpc.CallOption) (*DispatchComponentResponse, error)
	// Streaming dispatch for components that yield chunks.
	DispatchComponentStream(ctx context.Context, in *DispatchComponentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DispatchComponentResponse], error)
	// Forward a dispatch to a peer coordinator that owns the target worker's stream.
	ForwardDispatch(ctx context.Context, in *ForwardDispatchRequest, opts ...grpc.CallOption) (*DispatchComponentResponse, error)
	// Forward a streaming dispatch to a peer coordinator.
	ForwardDispatchStream(ctx context.Context, in *ForwardDispatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DispatchComponentResponse], error)
	// Forward a fire-and-forget dispatch to a peer coordinator.
	// Returns immediately after the dispatch is sent to the worker stream,
	// without waiting for the worker to complete execution.
	ForwardDispatchFireAndForget(ctx context.Context, in *ForwardDispatchRequest, opts ...grpc.CallOption) (*ForwardDispatchAck, error)
	// Release an active dispatch entry after the run reaches a terminal state.
	// Terminal records are observed by the partition owner, while the active
	// dispatch entry lives on the coordinator that owns the worker stream.
	ReleaseActiveDispatch(ctx context.Context, in *ReleaseActiveDispatchRequest, opts ...grpc.CallOption) (*ReleaseActiveDispatchAck, error)
}

type workerCoordinatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerCoordinatorServiceClient(cc grpc.ClientConnInterface) WorkerCoordinatorServiceClient {
	return &workerCoordinatorServiceClient{cc}
}

func (c *workerCoordinatorServiceClient) WorkerStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ServiceMessage, RuntimeMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerCoordinatorService_ServiceDesc.Streams[0], WorkerCoordinatorService_WorkerStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ServiceMessage, RuntimeMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerCoordinatorService_WorkerStreamClient = grpc.BidiStreamingClient[ServiceMessage, RuntimeMessage]

func (c *workerCoordinatorServiceClient) ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkersResponse)
	err := c.cc.Invoke(ctx, WorkerCoordinatorService_ListWorkers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerCoordinatorServiceClient) DispatchComponent(ctx context.Context, in *DispatchComponentRequest, opts ...grpc.CallOption) (*DispatchComponentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchComponentResponse)
	err := c.cc.Invoke(ctx, WorkerCoordinatorService_DispatchComponent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerCoordinatorServiceClient) DispatchComponentStream(ctx context.Context, in *DispatchComponentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DispatchComponentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerCoordinatorService_ServiceDesc.Streams[1], WorkerCoordinatorService_DispatchComponentStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DispatchComponentRequest, DispatchComponentResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerCoordinatorService_DispatchComponentStreamClient = grpc.ServerStreamingClient[DispatchComponentResponse]

func (c *workerCoordinatorServiceClient) ForwardDispatch(ctx context.Context, in *ForwardDispatchRequest, opts ...grpc.CallOption) (*DispatchComponentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchComponentResponse)
	err := c.cc.Invoke(ctx, WorkerCoordinatorService_ForwardDispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerCoordinatorServiceClient) ForwardDispatchStream(ctx context.Context, in *ForwardDispatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DispatchComponentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerCoordinatorService_ServiceDesc.Streams[2], WorkerCoordinatorService_ForwardDispatchStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ForwardDispatchRequest, DispatchComponentResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerCoordinatorService_ForwardDispatchStreamClient = grpc.ServerStreamingClient[DispatchComponentResponse]

func (c *workerCoordinatorServiceClient) ForwardDispatchFireAndForget(ctx context.Context, in *ForwardDispatchRequest, opts ...grpc.CallOption) (*ForwardDispatchAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardDispatchAck)
	err := c.cc.Invoke(ctx, WorkerCoordinatorService_ForwardDispatchFireAndForget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerCoordinatorServiceClient) ReleaseActiveDispatch(ctx context.Context, in *ReleaseActiveDispatchRequest, opts ...grpc.CallOption) (*ReleaseActiveDispatchAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseActiveDispatchAck)
	err := c.cc.Invoke(ctx, WorkerCoordinatorService_ReleaseActiveDispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerCoordinatorServiceServer is the server API for WorkerCoordinatorService service.
// All implementations must embed UnimplementedWorkerCoordinatorServiceServer
// for forward compatibility.
//
// WorkerCoordinatorService manages worker lifecycle and task dispatch.
//
// All state operations (signals, approvals, timers, checkpoints, journal writes,
// job queue, ephemeral event streams) are handled by EngineService. The coordinator
// is responsible ONLY for:
// - Worker stream lifecycle (registration, heartbeat, dispatch, response routing)
// - Task dispatch and worker selection
// - Inter-coordinator forwarding (disaggregated mode)
type WorkerCoordinatorServiceServer interface {
	// Main stream — bidirectional communication for worker lifecycle and task execution.
	// First message from worker must be ServiceRegistration.
	WorkerStream(grpc.BidiStreamingServer[ServiceMessage, RuntimeMessage]) error
	// List registered workers.
	ListWorkers(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error)
	// Dispatch a component to a registered worker (synchronous, waits for response).
	DispatchComponent(context.Context, *DispatchComponentRequest) (*DispatchComponentResponse, error)
	// Streaming dispatch for components that yield chunks.
	DispatchComponentStream(*DispatchComponentRequest, grpc.ServerStreamingServer[DispatchComponentResponse]) error
	// Forward a dispatch to a peer coordinator that owns the target worker's stream.
	ForwardDispatch(context.Context, *ForwardDispatchRequest) (*DispatchComponentResponse, error)
	// Forward a streaming dispatch to a peer coordinator.
	ForwardDispatchStream(*ForwardDispatchRequest, grpc.ServerStreamingServer[DispatchComponentResponse]) error
	// Forward a fire-and-forget dispatch to a peer coordinator.
	// Returns immediately after the dispatch is sent to the worker stream,
	// without waiting for the worker to complete execution.
	ForwardDispatchFireAndForget(context.Context, *ForwardDispatchRequest) (*ForwardDispatchAck, error)
	// Release an active dispatch entry after the run reaches a terminal state.
	// Terminal records are observed by the partition owner, while the active
	// dispatch entry lives on the coordinator that owns the worker stream.
	ReleaseActiveDispatch(context.Context, *ReleaseActiveDispatchRequest) (*ReleaseActiveDispatchAck, error)
	mustEmbedUnimplementedWorkerCoordinatorServiceServer()
}

// UnimplementedWorkerCoordinatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerCoordinatorServiceServer struct{}

func (UnimplementedWorkerCoordinatorServiceServer) WorkerStream(grpc.BidiStreamingServer[ServiceMessage, RuntimeMessage]) error {
	return status.Error(codes.Unimplemented, "method WorkerStream not implemented")
}
func (UnimplementedWorkerCoordinatorServiceServer) ListWorkers(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkers not implemented")
}
func (UnimplementedWorkerCoordinatorServiceServer) DispatchComponent(context.Context, *DispatchComponentRequest) (*DispatchComponentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DispatchComponent not implemented")
}
func (UnimplementedWorkerCoordinatorServiceServer) DispatchComponentStream(*DispatchComponentRequest, grpc.ServerStreamingServer[DispatchComponentResponse]) error {
	return status.Error(codes.Unimplemented, "method DispatchComponentStream not implemented")
}
func (UnimplementedWorkerCoordinatorServiceServer) ForwardDispatch(context.Context, *ForwardDispatchRequest) (*DispatchComponentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardDispatch not implemented")
}
func (UnimplementedWorkerCoordinatorServiceServer) ForwardDispatchStream(*ForwardDispatchRequest, grpc.ServerStreamingServer[DispatchComponentResponse]) error {
	return status.Error(codes.Unimplemented, "method ForwardDispatchStream not implemented")
}
func (UnimplementedWorkerCoordinatorServiceServer) ForwardDispatchFireAndForget(context.Context, *ForwardDispatchRequest) (*ForwardDispatchAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardDispatchFireAndForget not implemented")
}
func (UnimplementedWorkerCoordinatorServiceServer) ReleaseActiveDispatch(context.Context, *ReleaseActiveDispatchRequest) (*ReleaseActiveDispatchAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseActiveDispatch not implemented")
}
func (UnimplementedWorkerCoordinatorServiceServer) mustEmbedUnimplementedWorkerCoordinatorServiceServer() {
}
func (UnimplementedWorkerCoordinatorServiceServer) testEmbeddedByValue() {}

// UnsafeWorkerCoordinatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerCoordinatorServiceServer will
// result in compilation errors.
type UnsafeWorkerCoordinatorServiceServer interface {
	mustEmbedUnimplementedWorkerCoordinatorServiceServer()
}

func RegisterWorkerCoordinatorServiceServer(s grpc.ServiceRegistrar, srv WorkerCoordinatorServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkerCoordinatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerCoordinatorService_ServiceDesc, srv)
}

func _WorkerCoordinatorService_WorkerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerCoordinatorServiceServer).WorkerStream(&grpc.GenericServerStream[ServiceMessage, RuntimeMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerCoordinatorService_WorkerStreamServer = grpc.BidiStreamingServer[ServiceMessage, RuntimeMessage]

func _WorkerCoordinatorService_ListWorkers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerCoordinatorServiceServer).ListWorkers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerCoordinatorService_ListWorkers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerCoordinatorServiceServer).ListWorkers(ctx, req.(*ListWorkersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerCoordinatorService_DispatchComponent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchComponentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerCoordinatorServiceServer).DispatchComponent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerCoordinatorService_DispatchComponent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerCoordinatorServiceServer).DispatchComponent(ctx, req.(*DispatchComponentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerCoordinatorService_DispatchComponentStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DispatchComponentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerCoordinatorServiceServer).DispatchComponentStream(m, &grpc.GenericServerStream[DispatchComponentRequest, DispatchComponentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerCoordinatorService_DispatchComponentStreamServer = grpc.ServerStreamingServer[DispatchComponentResponse]

func _WorkerCoordinatorService_ForwardDispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardDispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerCoordinatorServiceServer).ForwardDispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerCoordinatorService_ForwardDispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerCoordinatorServiceServer).ForwardDispatch(ctx, req.(*ForwardDispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerCoordinatorService_ForwardDispatchStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ForwardDispatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerCoordinatorServiceServer).ForwardDispatchStream(m, &grpc.GenericServerStream[ForwardDispatchRequest, DispatchComponentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerCoordinatorService_ForwardDispatchStreamServer = grpc.ServerStreamingServer[DispatchComponentResponse]

func _WorkerCoordinatorService_ForwardDispatchFireAndForget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardDispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerCoordinatorServiceServer).ForwardDispatchFireAndForget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerCoordinatorService_ForwardDispatchFireAndForget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerCoordinatorServiceServer).ForwardDispatchFireAndForget(ctx, req.(*ForwardDispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerCoordinatorService_ReleaseActiveDispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseActiveDispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerCoordinatorServiceServer).ReleaseActiveDispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerCoordinatorService_ReleaseActiveDispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerCoordinatorServiceServer).ReleaseActiveDispatch(ctx, req.(*ReleaseActiveDispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerCoordinatorService_ServiceDesc is the grpc.ServiceDesc for WorkerCoordinatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerCoordinatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.WorkerCoordinatorService",
	HandlerType: (*WorkerCoordinatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListWorkers",
			Handler:    _WorkerCoordinatorService_ListWorkers_Handler,
		},
		{
			MethodName: "DispatchComponent",
			Handler:    _WorkerCoordinatorService_DispatchComponent_Handler,
		},
		{
			MethodName: "ForwardDispatch",
			Handler:    _WorkerCoordinatorService_ForwardDispatch_Handler,
		},
		{
			MethodName: "ForwardDispatchFireAndForget",
			Handler:    _WorkerCoordinatorService_ForwardDispatchFireAndForget_Handler,
		},
		{
			MethodName: "ReleaseActiveDispatch",
			Handler:    _WorkerCoordinatorService_ReleaseActiveDispatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WorkerStream",
			Handler:       _WorkerCoordinatorService_WorkerStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "DispatchComponentStream",
			Handler:       _WorkerCoordinatorService_DispatchComponentStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ForwardDispatchStream",
			Handler:       _WorkerCoordinatorService_ForwardDispatchStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/v1/worker_coordinator.proto",
}
